# Generated by Django 5.0.3 on 2024-05-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbolistas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futbolistas',
            old_name='WorldChampion',
            new_name='worldchampion',
        ),
    ]
