# Generated by Django 5.0.3 on 2024-06-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolistas', '0002_rename_worldchampion_futbolistas_worldchampion'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('funkos', models.ManyToManyField(blank=True, to='futbolistas.futbolistas')),
            ],
        ),
    ]
