# Generated by Django 5.0.3 on 2024-06-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolistas', '0004_rename_futbolistas_futbolista_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('futbolistas', models.ManyToManyField(blank=True, to='futbolistas.futbolista')),
            ],
        ),
    ]
