# Generated by Django 5.0.3 on 2024-06-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolistas', '0006_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
