# Generated by Django 5.0.3 on 2024-06-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolistas', '0007_estadio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadio',
            name='capacidad',
            field=models.CharField(max_length=128),
        ),
    ]
